###  Load Files

In [2]:
import pandas as pd
# Load the Excel file to inspect sheet names
excel_path = "risk-factors-prevalence.xlsx"
xls = pd.ExcelFile(excel_path)
sheet_names = xls.sheet_names
sheet_names

FileNotFoundError: [Errno 2] No such file or directory: 'risk-factors-prevalence.xlsx'

### 1.3 PHN_HBP_SEX_2017-18

In [11]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df2 = xls.parse('1.3 PHN_HBP_SEX_2017-18', skiprows=9)
df2.head()

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

,Unnamed: 0,Unnamed: 1,Persons aged 18+,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Females aged 18+,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Code,Name,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio,...,95% CI rate ratio,NaN,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio
1,NaN,Australia,4255962.575278,22.813936,(22.0–23.6),18655100,21.78305,(21.0–22.6),1,–,...,–,NaN,1929924.281615,20.286158,(19.3–21.3),9513503,18.91277,(18.0–19.9),1,–
2,PHN101,Central and Eastern Sydney,265714,20.805,(20.1–21.6),1277175,21.886,(21.1–22.6),1.00529,(1.0–1.1),...,(1.0–1.1),NaN,113988.6,17.604,(16.6–18.6),647508.3,18.349,(17.6–19.1),0.96948,(0.9–1.0)
3,PHN102,Northern Sydney,160172.1,22.619,(21.8–23.4),708127.2,21.43,(20.6–22.2),0.98433,(0.9–1.0),...,(0.9–1.1),NaN,72798.6,19.838,(18.9–20.8),366973.3,18.342,(17.6–19.1),0.96911,(0.9–1.0)
4,PHN103,Western Sydney,155645.6,21.484,(20.7–22.3),724473.6,22.488,(21.7–23.3),1.03294,(1.0–1.1),...,(1.0–1.1),NaN,69287.37,19.168,(18.4–20.0),361469.4,19.786,(19.0–20.6),1.04538,(1.0–1.1)

In [12]:
# Load with multi-level header (first 2 rows after skipping 9)
df2_multi = xls.parse('1.3 PHN_HBP_SEX_2017-18', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df2_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df2_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df2_multi = df2_multi[df2_multi[df2_multi.columns[0]] != 'Code']
df2_multi = df2_multi[df2_multi[df2_multi.columns[0]].notna()]

# Reset index for clarity
df2_multi.reset_index(drop=True, inplace=True)

for col in df2_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18+ - Number'
'Persons aged 18+ - Proportion (%)'
'Persons aged 18+ - 95% CI of proportion'
'Persons aged 18+ - Population'
'Persons aged 18+ - Age-standardised rate (per 100)'
'Persons aged 18+ - 95% CI standardised rate'
'Persons aged 18+ - Rate ratio  (relative to all of Australia)'
'Persons aged 18+ - 95% CI rate ratio'
'Persons aged 18+ - 95% CI rate ratio.1'
'Males aged 18+ - Number'
'Males aged 18+ - Proportion (%)'
'Males aged 18+ - 95% CI of proportion'
'Males aged 18+ - Population'
'Males aged 18+ - Age-standardised rate (per 100)'
'Males aged 18+ - 95% CI standardised rate'
'Males aged 18+ - Rate ratio  (relative to all of Australia)'
'Males aged 18+ - 95% CI rate ratio'
'Males aged 18+ - 95% CI rate ratio.1'
'Females aged 18+ - Number'
'Females aged 18+ - Proportion (%)'
'Females aged 18+ - 95% CI of proportion'
'Females aged 18+ - Population'
'Females aged 18+ - Age-standardised rate (per 100)'
'Females aged 18+ - 95% CI standardised rate'
'Females aged 18+ - Rate ratio  (relative to all of Australia)'
'Females aged 18+ - 95% CI rate ratio'

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [17]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df2_multi.rename(columns={
    df2_multi.columns[0]: "Code",
    df2_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean column names
df2_multi.columns = df2_multi.columns.str.strip()

# Step 3: Select only relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18+ - Number',
    'Persons aged 18+ - Proportion (%)',
    'Persons aged 18+ - 95% CI of proportion',
    'Persons aged 18+ - Population',
    'Persons aged 18+ - Age-standardised rate (per 100)',
    'Persons aged 18+ - 95% CI standardised rate',
    'Persons aged 18+ - Rate ratio  (relative to all of Australia)',
    'Persons aged 18+ - 95% CI rate ratio',
    'Persons aged 18+ - 95% CI rate ratio.1',
    'Males aged 18+ - Number',
    'Males aged 18+ - Proportion (%)',
    'Males aged 18+ - 95% CI of proportion',
    'Males aged 18+ - Population',
    'Males aged 18+ - Age-standardised rate (per 100)',
    'Males aged 18+ - 95% CI standardised rate',
    'Males aged 18+ - Rate ratio  (relative to all of Australia)',
    'Males aged 18+ - 95% CI rate ratio',
    'Males aged 18+ - 95% CI rate ratio.1',
    'Females aged 18+ - Number',
    'Females aged 18+ - Proportion (%)',
    'Females aged 18+ - 95% CI of proportion',
    'Females aged 18+ - Population',
    'Females aged 18+ - Age-standardised rate (per 100)',
    'Females aged 18+ - 95% CI standardised rate',
    'Females aged 18+ - Rate ratio  (relative to all of Australia)',
    'Females aged 18+ - 95% CI rate ratio'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df2_multi.columns]
df2_selected = df2_multi[selected_columns].copy()

# Step 4: Melt to long format
df2_final = pd.melt(
    df2_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df2_final["Gender"] = df2_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df2_final["AgeGroup"] = df2_final["Group_Metric"].str.extract(r'aged (.*) -')
df2_final["Metric"] = df2_final["Group_Metric"].str.extract(r'- (.*)$')
df2_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df2_final["Metric"] = df2_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df2_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
def split_ci(ci_value):
    if isinstance(ci_value, str) and '–' in ci_value:
        parts = ci_value.strip("()").split("–")
        try:
            return float(parts[0]), float(parts[1])
        except:
            return None, None
    return None, None

for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
    df_wide.drop(columns=ci_col, inplace=True)

# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()

# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "High blood pressure"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)

# Step 11: Export to CSV
hbp_df_clean.to_csv("PHN_HBP_SEX_2017-18.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_HBP_SEX_2017-18.csv' successfully!")

Missing values after cleaning:
 Metric
Code                          0
Region                        0
Gender                        0
AgeGroup                      0
Age_Standardised_Rate         0
Number                        0
Population                    0
Rate_Ratio                    0
CI_Proportion_Lower           0
CI_Proportion_Upper           0
CI_Standardised_Rate_Lower    0
CI_Standardised_Rate_Upper    0
CI_Rate_Ratio_Lower           0
CI_Rate_Ratio_Upper           0
Proportion (%)                0
Risk_Factor                   0
dtype: int64
 Final shape: (93, 16)
Saved as 'PHN_HBP_SEX_2017-18.csv' successfully!

### 1.4 PHN_HBP_AGE&SEX

In [18]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df3 = xls.parse('1.4 PHN_HBP_AGE&SEX', skiprows=9)
df3.head()

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

,Unnamed: 0,Unnamed: 1,Persons aged 18–54,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Persons aged 55–74,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Females aged 55–74,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Females aged 75+,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Code,Name,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,...,NaN,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,95% CI of proportion
1,NaN,Australia,1788630.566647,14.638881,12218356,(13.8–15.5),NaN,1812401.839997,36.379557,4981923.951862,...,NaN,865990.825246,33.873472,2556545.794198,(31.5–36.3),NaN,359906.092609,45.574163,789715.205802,(41.8–49.4)
2,PHN101,Central and Eastern Sydney,129928,14.136,919113.8,(13.3–14.9),NaN,97390.47,35.942,270965.3,...,NaN,46188.58,32.992,140001.2,(31.3–34.7),NaN,20719.93,42.809,48400.83,(40.7–44.9)
3,PHN102,Northern Sydney,71154.7,15.146,469801.6,(14.3–15.9),NaN,62875.53,35.35,177864.8,...,NaN,30309.23,32.815,92363.79,(31.2–34.5),NaN,14163.89,42.008,33717.17,(39.9–44.1)
4,PHN103,Western Sydney,78957.18,15.078,523649.6,(14.3–15.9),NaN,58813.15,36.602,160684.8,...,NaN,28355.82,34.512,82163.25,(32.9–36.1),NaN,9666.473,43.717,22111.71,(41.7–45.8)

In [19]:
# Load with multi-level header (first 2 rows after skipping 9)
df3_multi = xls.parse('1.4 PHN_HBP_AGE&SEX', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df3_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df3_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df3_multi = df3_multi[df3_multi[df3_multi.columns[0]] != 'Code']
df3_multi = df3_multi[df3_multi[df3_multi.columns[0]].notna()]

# Reset index for clarity
df3_multi.reset_index(drop=True, inplace=True)

for col in df3_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18–54 - Number'
'Persons aged 18–54 - Proportion (%)'
'Persons aged 18–54 - Population'
'Persons aged 18–54 - 95% CI of proportion'
'Persons aged 18–54 - 95% CI of proportion.1'
'Persons aged 55–74 - Number'
'Persons aged 55–74 - Proportion (%)'
'Persons aged 55–74 - Population'
'Persons aged 55–74 - 95% CI of proportion'
'Persons aged 55–74 - 95% CI of proportion.1'
'Persons aged 75+ - Number'
'Persons aged 75+ - Proportion (%)'
'Persons aged 75+ - Population'
'Persons aged 75+ - 95% CI of proportion'
'Persons aged 75+ - 95% CI of proportion.1'
'Males aged 18–54 - Number'
'Males aged 18–54 - Proportion (%)'
'Males aged 18–54 - Population'
'Males aged 18–54 - 95% CI of proportion'
'Males aged 18–54 - 95% CI of proportion.1'
'Males aged 55–74 - Number'
'Males aged 55–74 - Proportion (%)'
'Males aged 55–74 - Population'
'Males aged 55–74 - 95% CI of proportion'
'Males aged 55–74 - 95% CI of proportion.1'
'Males aged 75+ - Number'
'Males aged 75+ - Proportion (%)'
'Males aged 75+ - Population'
'Males aged 75+ - 95% CI of proportion'
'Males aged 75+ - 95% CI of proportion.1'
'Females aged 18–54 - Number'
'Females aged 18–54 - Proportion (%)'
'Females aged 18–54 - Population'
'Females aged 18–54 - 95% CI of proportion'
'Females aged 18–54 - 95% CI of proportion.1'
'Females aged 55–74 - Number'
'Females aged 55–74 - Proportion (%)'
'Females aged 55–74 - Population'
'Females aged 55–74 - 95% CI of proportion'
'Females aged 55–74 - 95% CI of proportion.1'
'Females aged 75+ - Number'
'Females aged 75+ - Proportion (%)'
'Females aged 75+ - Population'
'Females aged 75+ - 95% CI of proportion'

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [22]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df3_multi.rename(columns={
    df3_multi.columns[0]: "Code",
    df3_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean column names
df3_multi.columns = df3_multi.columns.str.strip()

# Step 3: Select only relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18–54 - Number',
    'Persons aged 18–54 - Proportion (%)',
    'Persons aged 18–54 - Population',
    'Persons aged 18–54 - 95% CI of proportion',
    'Persons aged 18–54 - 95% CI of proportion.1',
    'Persons aged 55–74 - Number',
    'Persons aged 55–74 - Proportion (%)',
    'Persons aged 55–74 - Population',
    'Persons aged 55–74 - 95% CI of proportion',
    'Persons aged 55–74 - 95% CI of proportion.1',
    'Persons aged 75+ - Number',
    'Persons aged 75+ - Proportion (%)',
    'Persons aged 75+ - Population',
    'Persons aged 75+ - 95% CI of proportion',
    'Persons aged 75+ - 95% CI of proportion.1',
    'Males aged 18–54 - Number',
    'Males aged 18–54 - Proportion (%)',
    'Males aged 18–54 - Population',
    'Males aged 18–54 - 95% CI of proportion',
    'Males aged 18–54 - 95% CI of proportion.1',
    'Males aged 55–74 - Number',
    'Males aged 55–74 - Proportion (%)',
    'Males aged 55–74 - Population',
    'Males aged 55–74 - 95% CI of proportion',
    'Males aged 55–74 - 95% CI of proportion.1',
    'Males aged 75+ - Number',
    'Males aged 75+ - Proportion (%)',
    'Males aged 75+ - Population',
    'Males aged 75+ - 95% CI of proportion',
    'Males aged 75+ - 95% CI of proportion.1',
    'Females aged 18–54 - Number',
    'Females aged 18–54 - Proportion (%)',
    'Females aged 18–54 - Population',
    'Females aged 18–54 - 95% CI of proportion',
    'Females aged 18–54 - 95% CI of proportion.1',
    'Females aged 55–74 - Number',
    'Females aged 55–74 - Proportion (%)',
    'Females aged 55–74 - Population',
    'Females aged 55–74 - 95% CI of proportion',
    'Females aged 55–74 - 95% CI of proportion.1',
    'Females aged 75+ - Number',
    'Females aged 75+ - Proportion (%)',
    'Females aged 75+ - Population',
    'Females aged 75+ - 95% CI of proportion'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df3_multi.columns]
df3_selected = df3_multi[selected_columns].copy()

# Step 4: Melt to long format
df3_final = pd.melt(
    df3_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df3_final["Gender"] = df3_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df3_final["AgeGroup"] = df3_final["Group_Metric"].str.extract(r'aged (.*) -')
df3_final["Metric"] = df3_final["Group_Metric"].str.extract(r'- (.*)$')
df3_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df3_final["Metric"] = df3_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df3_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
def split_ci(ci_value):
    if isinstance(ci_value, str) and '–' in ci_value:
        parts = ci_value.strip("()").split("–")
        try:
            return float(parts[0]), float(parts[1])
        except:
            return None, None
    return None, None

for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    if ci_col in df_wide.columns:
        df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
        df_wide.drop(columns=ci_col, inplace=True)

# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
if 'Age_Standardised_Rate' in df_wide.columns:
    hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()
else:
    hbp_df_clean = df_wide.copy()
    print("Warning: 'Age_Standardised_Rate' column not found. Skipping dropna on this column.")


# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "High blood pressure"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 11: Export final tidy CSV
hbp_df_clean.to_csv("PHN_HBP_AGE_SEX.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_HBP_AGE_SEX.csv' successfully!")

Warning: 'Age_Standardised_Rate' column not found. Skipping dropna on this column.
Missing values after cleaning:
 Metric
Code                   0
Region                 0
Gender                 0
AgeGroup               0
Number                 8
Population             8
CI_Proportion_Lower    0
CI_Proportion_Upper    0
Proportion (%)         8
Risk_Factor            0
dtype: int64
 Final shape: (279, 10)
Saved as 'PHN_HBP_AGE_SEX.csv' successfully!

### 2.3 PHN_IPA_SEX_2017-18

In [23]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df8 = xls.parse('2.3 PHN_IPA_SEX_2017-18', skiprows=9)
df8.head()

,Unnamed: 0,Unnamed: 1,Persons aged 18+,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Females aged 18+,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Code,Name,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio,...,95% CI rate ratio,NaN,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio
1,NaN,Australia,11998999.988338,64.668432,(63.7–65.6),18554648.241505,64.406889,(63.4–65.5),1,–,...,–,NaN,6104885.065911,64.478186,(63.1–65.9),9468140.191203,64.083673,(62.7–65.5),1,–
2,PHN101,Central and Eastern Sydney,694712.4,54.394,(52.2–56.6),1277175,55.39,(53.2–57.6),0.86112,(0.8–0.9),...,(0.8–0.9),NaN,352578.1,54.452,(52.2–56.7),647508.3,54.993,(52.8–57.2),0.85824,(0.8–0.9)
3,PHN102,Northern Sydney,376413.3,53.156,(51.1–55.2),708127.2,53.236,(51.2–55.3),0.82764,(0.8–0.9),...,(0.8–0.9),NaN,195776.1,53.349,(51.2–55.5),366973.3,52.984,(50.9–55.0),0.82688,(0.8–0.9)
4,PHN103,Western Sydney,489033.4,67.502,(65.7–69.3),724473.6,68.509,(66.7–70.3),1.06508,(1.0–1.1),...,(1.0–1.1),NaN,244243,67.569,(65.8–69.3),361469.4,68.159,(66.3–70.0),1.0637,(1.0–1.1)

In [24]:
# Load with multi-level header (first 2 rows after skipping 9)
df8_multi = xls.parse('2.3 PHN_IPA_SEX_2017-18', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df8_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df8_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df8_multi = df8_multi[df8_multi[df8_multi.columns[0]] != 'Code']
df8_multi = df8_multi[df8_multi[df8_multi.columns[0]].notna()]

# Reset index for clarity
df8_multi.reset_index(drop=True, inplace=True)

for col in df8_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18+ - Number'
'Persons aged 18+ - Proportion (%)'
'Persons aged 18+ - 95% CI of proportion'
'Persons aged 18+ - Population'
'Persons aged 18+ - Age-standardised rate (per 100)'
'Persons aged 18+ - 95% CI standardised rate'
'Persons aged 18+ - Rate ratio  (relative to all of Australia)'
'Persons aged 18+ - 95% CI rate ratio'
'Persons aged 18+ - 95% CI rate ratio.1'
'Males aged 18+ - Number'
'Males aged 18+ - Proportion (%)'
'Males aged 18+ - 95% CI of proportion'
'Males aged 18+ - Population'
'Males aged 18+ - Age-standardised rate (per 100)'
'Males aged 18+ - 95% CI standardised rate'
'Males aged 18+ - Rate ratio  (relative to all of Australia)'
'Males aged 18+ - 95% CI rate ratio'
'Males aged 18+ - 95% CI rate ratio.1'
'Females aged 18+ - Number'
'Females aged 18+ - Proportion (%)'
'Females aged 18+ - 95% CI of proportion'
'Females aged 18+ - Population'
'Females aged 18+ - Age-standardised rate (per 100)'
'Females aged 18+ - 95% CI standardised rate'
'Females aged 18+ - Rate ratio  (relative to all of Australia)'
'Females aged 18+ - 95% CI rate ratio'

In [55]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df8_multi.rename(columns={
    df8_multi.columns[0]: "Code",
    df8_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean up column names
df8_multi.columns = df8_multi.columns.str.strip()

# Step 3: Select relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18+ - Number',
    'Persons aged 18+ - Proportion (%)',
    'Persons aged 18+ - 95% CI of proportion',
    'Persons aged 18+ - Population',
    'Persons aged 18+ - Age-standardised rate (per 100)',
    'Persons aged 18+ - 95% CI standardised rate',
    'Persons aged 18+ - Rate ratio  (relative to all of Australia)',
    'Persons aged 18+ - 95% CI rate ratio',
    'Males aged 18+ - Number',
    'Males aged 18+ - Proportion (%)',
    'Males aged 18+ - 95% CI of proportion',
    'Males aged 18+ - Population',
    'Males aged 18+ - Age-standardised rate (per 100)',
    'Males aged 18+ - 95% CI standardised rate',
    'Males aged 18+ - Rate ratio  (relative to all of Australia)',
    'Males aged 18+ - 95% CI rate ratio',
    'Females aged 18+ - Number',
    'Females aged 18+ - Proportion (%)',
    'Females aged 18+ - 95% CI of proportion',
    'Females aged 18+ - Population',
    'Females aged 18+ - Age-standardised rate (per 100)',
    'Females aged 18+ - 95% CI standardised rate',
    'Females aged 18+ - Rate ratio  (relative to all of Australia)',
    'Females aged 18+ - 95% CI rate ratio'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df8_multi.columns]
df8_selected = df8_multi[selected_columns].copy()

# Step 4: Melt to long format
df8_final = pd.melt(
    df8_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df8_final["Gender"] = df8_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df8_final["AgeGroup"] = df8_final["Group_Metric"].str.extract(r'aged (.*) -')
df8_final["Metric"] = df8_final["Group_Metric"].str.extract(r'- (.*)$')
df8_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df8_final["Metric"] = df8_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df8_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
def split_ci(ci_value):
    if isinstance(ci_value, str) and '–' in ci_value:
        parts = ci_value.strip("()").split("–")
        try:
            return float(parts[0]), float(parts[1])
        except:
            return None, None
    return None, None

for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
    df_wide.drop(columns=ci_col, inplace=True)

# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()

# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Insufficient Physical Activity"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)


# Step 12: Save to CSV
hbp_df_clean.to_csv("PHN_IPA_SEX_2017-18.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_IPA_SEX_2017-18.csv' successfully!")

Missing values after cleaning:
 Metric
Code                          0
Region                        0
Gender                        0
AgeGroup                      0
Age_Standardised_Rate         0
Number                        0
Population                    0
Rate_Ratio                    0
CI_Proportion_Lower           0
CI_Proportion_Upper           0
CI_Standardised_Rate_Lower    0
CI_Standardised_Rate_Upper    0
CI_Rate_Ratio_Lower           0
CI_Rate_Ratio_Upper           0
Proportion (%)                0
Risk_Factor                   0
dtype: int64
 Final shape: (93, 16)
Saved as 'PHN_IPA_SEX_2017-18.csv' successfully!

### 2.4 PHN_IPA_AGE&SEX

In [26]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df9 = xls.parse('2.4 PHN_IPA_AGE&SEX', skiprows=9)
df9.head()

,Unnamed: 0,Unnamed: 1,Persons aged 18–54,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Persons aged 55–74,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Females aged 55–74,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Females aged 75+,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Code,Name,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,...,NaN,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,95% CI of proportion
1,NaN,Australia,7519952.007072,61.945056,12139713.028835,(60.6–63.3),NaN,3326032.561189,67.00023,4964210.685802,...,NaN,1688948.495354,66.322628,2546564.485179,(63.5–69.2),NaN,647072.244057,82.290049,786331.09742,(79.5–85.1)
2,PHN101,Central and Eastern Sydney,467489,50.863,919113.8,(48.5–53.3),NaN,160677,59.298,270965.3,...,NaN,81794.4,58.424,140001.2,(55.7–61.2),NaN,38924.92,80.422,48400.83,(77.5–83.4)
3,PHN102,Northern Sydney,236111.9,50.258,469801.6,(48.1–52.4),NaN,97010.96,54.542,177864.8,...,NaN,49532.17,53.627,92363.79,(50.6–56.6),NaN,25679,76.16,33717.17,(72.8–79.5)
4,PHN103,Western Sydney,342223.9,65.354,523649.6,(63.3–67.4),NaN,114228.8,71.089,160684.8,...,NaN,58056.54,70.66,82163.25,(68.7–72.7),NaN,18809.59,85.066,22111.71,(82.8–87.4)

In [27]:
# Load with multi-level header (first 2 rows after skipping 9)
df9_multi = xls.parse('2.4 PHN_IPA_AGE&SEX', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df9_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df9_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df9_multi = df9_multi[df9_multi[df9_multi.columns[0]] != 'Code']
df9_multi = df9_multi[df9_multi[df9_multi.columns[0]].notna()]

# Reset index for clarity
df9_multi.reset_index(drop=True, inplace=True)

for col in df9_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18–54 - Number'
'Persons aged 18–54 - Proportion (%)'
'Persons aged 18–54 - Population'
'Persons aged 18–54 - 95% CI of proportion'
'Persons aged 18–54 - 95% CI of proportion.1'
'Persons aged 55–74 - Number'
'Persons aged 55–74 - Proportion (%)'
'Persons aged 55–74 - Population'
'Persons aged 55–74 - 95% CI of proportion'
'Persons aged 55–74 - 95% CI of proportion.1'
'Persons aged 75+ - Number'
'Persons aged 75+ - Proportion (%)'
'Persons aged 75+ - Population'
'Persons aged 75+ - 95% CI of proportion'
'Persons aged 75+ - 95% CI of proportion.1'
'Males aged 18–54 - Number'
'Males aged 18–54 - Proportion (%)'
'Males aged 18–54 - Population'
'Males aged 18–54 - 95% CI of proportion'
'Males aged 18–54 - 95% CI of proportion.1'
'Males aged 55–74 - Number'
'Males aged 55–74 - Proportion (%)'
'Males aged 55–74 - Population'
'Males aged 55–74 - 95% CI of proportion'
'Males aged 55–74 - 95% CI of proportion.1'
'Males aged 75+ - Number'
'Males aged 75+ - Proportion (%)'
'Males aged 75+ - Population'
'Males aged 75+ - 95% CI of proportion'
'Males aged 75+ - 95% CI of proportion.1'
'Females aged 18–54 - Number'
'Females aged 18–54 - Proportion (%)'
'Females aged 18–54 - Population'
'Females aged 18–54 - 95% CI of proportion'
'Females aged 18–54 - 95% CI of proportion.1'
'Females aged 55–74 - Number'
'Females aged 55–74 - Proportion (%)'
'Females aged 55–74 - Population'
'Females aged 55–74 - 95% CI of proportion'
'Females aged 55–74 - 95% CI of proportion.1'
'Females aged 75+ - Number'
'Females aged 75+ - Proportion (%)'
'Females aged 75+ - Population'
'Females aged 75+ - 95% CI of proportion'

In [56]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df9_multi.rename(columns={
    df9_multi.columns[0]: "Code",
    df9_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean column names
df9_multi.columns = df9_multi.columns.str.strip()

# Step 3: Select only relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18–54 - Number',
    'Persons aged 18–54 - Proportion (%)',
    'Persons aged 18–54 - Population',
    'Persons aged 18–54 - 95% CI of proportion',
    'Persons aged 55–74 - Number',
    'Persons aged 55–74 - Proportion (%)',
    'Persons aged 55–74 - Population',
    'Persons aged 55–74 - 95% CI of proportion',
    'Persons aged 75+ - Number',
    'Persons aged 75+ - Proportion (%)',
    'Persons aged 75+ - Population',
    'Persons aged 75+ - 95% CI of proportion',
    'Males aged 18–54 - Number',
    'Males aged 18–54 - Proportion (%)',
    'Males aged 18–54 - Population',
    'Males aged 18–54 - 95% CI of proportion',
    'Males aged 55–74 - Number',
    'Males aged 55–74 - Proportion (%)',
    'Males aged 55–74 - Population',
    'Males aged 55–74 - 95% CI of proportion',
    'Males aged 75+ - Number',
    'Males aged 75+ - Proportion (%)',
    'Males aged 75+ - Population',
    'Males aged 75+ - 95% CI of proportion',
    'Females aged 18–54 - Number',
    'Females aged 18–54 - Proportion (%)',
    'Females aged 18–54 - Population',
    'Females aged 18–54 - 95% CI of proportion',
    'Females aged 55–74 - Number',
    'Females aged 55–74 - Proportion (%)',
    'Females aged 55–74 - Population',
    'Females aged 55–74 - 95% CI of proportion',
    'Females aged 75+ - Number',
    'Females aged 75+ - Proportion (%)',
    'Females aged 75+ - Population',
    'Females aged 75+ - 95% CI of proportion'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df9_multi.columns]
df9_selected = df9_multi[selected_columns].copy()

# Step 4: Melt to long format
df9_final = pd.melt(
    df9_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df9_final["Gender"] = df9_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df9_final["AgeGroup"] = df9_final["Group_Metric"].str.extract(r'aged (.*) -')
df9_final["Metric"] = df9_final["Group_Metric"].str.extract(r'- (.*)$')
df9_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df9_final["Metric"] = df9_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df9_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    if ci_col in df_wide.columns:
        df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
        df_wide.drop(columns=ci_col, inplace=True)
    else:
        print(f"Column '{ci_col}' not found in dataset. Skipping.")


# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
if 'Age_Standardised_Rate' in df_wide.columns:
    hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()
else:
    print(" Age_Standardised_Rate' not found. Skipping dropna on that column.")
    hbp_df_clean = df_wide.copy()


# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Insufficient Physical Activity"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 12: Export to CSV
hbp_df_clean.to_csv("PHN_IPA_AGE_SEX.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_IPA_AGE_SEX.csv' successfully!")

Column 'CI_Standardised_Rate' not found in dataset. Skipping.
Column 'CI_Rate_Ratio' not found in dataset. Skipping.
 Age_Standardised_Rate' not found. Skipping dropna on that column.
Missing values after cleaning:
 Metric
Code                   0
Region                 0
Gender                 0
AgeGroup               0
Number                 6
Population             6
CI_Proportion_Lower    0
CI_Proportion_Upper    0
Proportion (%)         6
Risk_Factor            0
dtype: int64
 Final shape: (279, 10)
Saved as 'PHN_IPA_AGE_SEX.csv' successfully!

### 3.3 PHN_OB_SEX_2017-18

In [31]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df33 = xls.parse('3.3 PHN_OB_SEX_2017-18', skiprows=9)
df33.head()

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

,Unnamed: 0,Unnamed: 1,Persons aged 18+,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Females aged 18+,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Code,Name,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio,...,95% CI rate ratio,NaN,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio
1,NaN,Australia,5846420.903245,31.339531,(30.4–32.3),18655100,30.842271,(29.9–31.7),1,–,...,–,NaN,2870814.987912,30.176214,(29.0–31.4),9513503,29.536465,(28.4–30.7),1,–
2,PHN101,Central and Eastern Sydney,299758.5,23.47,(22.9–24.0),1277175,23.729,(23.2–24.2),0.77006,(0.7–0.8),...,(0.7–0.8),NaN,144915.9,22.381,(21.9–22.9),647508.3,23.077,(22.6–23.6),0.78089,(0.7–0.8)
3,PHN102,Northern Sydney,145528,20.551,(19.9–21.2),708127.2,19.631,(19.0–20.3),0.63706,(0.6–0.7),...,(0.6–0.7),NaN,72221,19.68,(19.1–20.3),366973.3,19.099,(18.5–19.7),0.64628,(0.6–0.7)
4,PHN103,Western Sydney,203621.3,28.106,(26.8–29.4),724473.6,27.98,(26.7–29.3),0.908,(0.9–1.0),...,(0.8–0.9),NaN,98195.8,27.166,(25.8–28.5),361469.4,27.566,(26.3–28.9),0.93279,(0.9–1.0)

In [32]:
# Load with multi-level header (first 2 rows after skipping 9)
df33_multi = xls.parse('3.3 PHN_OB_SEX_2017-18', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df33_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df33_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df33_multi = df33_multi[df33_multi[df33_multi.columns[0]] != 'Code']
df33_multi = df33_multi[df33_multi[df33_multi.columns[0]].notna()]

# Reset index for clarity
df33_multi.reset_index(drop=True, inplace=True)

for col in df33_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18+ - Number'
'Persons aged 18+ - Proportion (%)'
'Persons aged 18+ - 95% CI of proportion'
'Persons aged 18+ - Population'
'Persons aged 18+ - Age-standardised rate (per 100)'
'Persons aged 18+ - 95% CI standardised rate'
'Persons aged 18+ - Rate ratio  (relative to all of Australia)'
'Persons aged 18+ - 95% CI rate ratio'
'Persons aged 18+ - 95% CI rate ratio.1'
'Males aged 18+ - Number'
'Males aged 18+ - Proportion (%)'
'Males aged 18+ - 95% CI of proportion'
'Males aged 18+ - Population'
'Males aged 18+ - Age-standardised rate (per 100)'
'Males aged 18+ - 95% CI standardised rate'
'Males aged 18+ - Rate ratio  (relative to all of Australia)'
'Males aged 18+ - 95% CI rate ratio'
'Males aged 18+ - 95% CI rate ratio.1'
'Females aged 18+ - Number'
'Females aged 18+ - Proportion (%)'
'Females aged 18+ - 95% CI of proportion'
'Females aged 18+ - Population'
'Females aged 18+ - Age-standardised rate (per 100)'
'Females aged 18+ - 95% CI standardised rate'
'Females aged 18+ - Rate ratio  (relative to all of Australia)'
'Females aged 18+ - 95% CI rate ratio'

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [57]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df33_multi.rename(columns={
    df33_multi.columns[0]: "Code",
    df33_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean column names
df33_multi.columns = df33_multi.columns.str.strip()

# Step 3: Select only relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18+ - Number',
    'Persons aged 18+ - Proportion (%)',
    'Persons aged 18+ - 95% CI of proportion',
    'Persons aged 18+ - Population',
    'Persons aged 18+ - Age-standardised rate (per 100)',
    'Persons aged 18+ - 95% CI standardised rate',
    'Persons aged 18+ - Rate ratio  (relative to all of Australia)',
    'Persons aged 18+ - 95% CI rate ratio',
    'Persons aged 18+ - 95% CI rate ratio.1',
    'Males aged 18+ - Number',
    'Males aged 18+ - Proportion (%)',
    'Males aged 18+ - 95% CI of proportion',
    'Males aged 18+ - Population',
    'Males aged 18+ - Age-standardised rate (per 100)',
    'Males aged 18+ - 95% CI standardised rate',
    'Males aged 18+ - Rate ratio  (relative to all of Australia)',
    'Males aged 18+ - 95% CI rate ratio',
    'Males aged 18+ - 95% CI rate ratio.1',
    'Females aged 18+ - Number',
    'Females aged 18+ - Proportion (%)',
    'Females aged 18+ - 95% CI of proportion',
    'Females aged 18+ - Population',
    'Females aged 18+ - Age-standardised rate (per 100)',
    'Females aged 18+ - 95% CI standardised rate',
    'Females aged 18+ - Rate ratio  (relative to all of Australia)',
    'Females aged 18+ - 95% CI rate ratio'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df33_multi.columns]
df33_selected = df33_multi[selected_columns].copy()

# Step 4: Melt to long format
df33_final = pd.melt(
    df33_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df33_final["Gender"] = df33_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df33_final["AgeGroup"] = df33_final["Group_Metric"].str.extract(r'aged (.*) -')
df33_final["Metric"] = df33_final["Group_Metric"].str.extract(r'- (.*)$')
df33_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df33_final["Metric"] = df33_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df33_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
def split_ci(ci_value):
    if isinstance(ci_value, str) and '–' in ci_value:
        parts = ci_value.strip("()").split("–")
        try:
            return float(parts[0]), float(parts[1])
        except:
            return None, None
    return None, None

for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
    df_wide.drop(columns=ci_col, inplace=True)

# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()

# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Obesity"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 12: Export to CSV
hbp_df_clean.to_csv("PHN_OB_SEX_2017-18.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_OB_SEX_2017-18.csv' successfully!")

Missing values after cleaning:
 Metric
Code                          0
Region                        0
Gender                        0
AgeGroup                      0
Age_Standardised_Rate         0
Number                        0
Population                    0
Rate_Ratio                    0
CI_Proportion_Lower           0
CI_Proportion_Upper           0
CI_Standardised_Rate_Lower    0
CI_Standardised_Rate_Upper    0
CI_Rate_Ratio_Lower           0
CI_Rate_Ratio_Upper           0
Proportion (%)                0
Risk_Factor                   0
dtype: int64
 Final shape: (93, 16)
Saved as 'PHN_OB_SEX_2017-18.csv' successfully!

### 3.4 PHN_OB_AGE&SEX

In [34]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df34 = xls.parse('3.4 PHN_OB_AGE&SEX', skiprows=9)
df34.head()

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

,Unnamed: 0,Unnamed: 1,Persons aged 18–54,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Persons aged 55–74,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Females aged 55–74,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Females aged 75+,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Code,Name,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,...,NaN,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,95% CI of proportion
1,NaN,Australia,3368833.166041,27.571902,12218356,(26.4–28.7),NaN,2000480.762592,40.154783,4981923.951862,...,NaN,985472.427064,38.547028,2556545.794198,(36.0–41.1),NaN,278676.562751,35.288236,789715.205802,(31.5–39.1)
2,PHN101,Central and Eastern Sydney,188678.5,20.528,919113.8,(20.0–21.0),NaN,86820.65,32.041,270965.3,...,NaN,42354.81,30.253,140001.2,(29.6–30.9),NaN,14274.53,29.492,48400.83,(28.7–30.3)
3,PHN102,Northern Sydney,83452.36,17.763,469801.6,(17.2–18.3),NaN,47759.08,26.851,177864.8,...,NaN,23564.75,25.513,92363.79,(24.7–26.3),NaN,8610.569,25.538,33717.17,(24.7–26.4)
4,PHN103,Western Sydney,131709.3,25.152,523649.6,(23.8–26.5),NaN,58876.39,36.641,160684.8,...,NaN,28671.76,34.896,82163.25,(33.2–36.6),NaN,7570.039,34.235,22111.71,(32.3–36.2)

In [35]:
# Load with multi-level header (first 2 rows after skipping 9)
df34_multi = xls.parse('3.4 PHN_OB_AGE&SEX', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df34_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df34_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df34_multi = df34_multi[df34_multi[df34_multi.columns[0]] != 'Code']
df34_multi = df34_multi[df34_multi[df34_multi.columns[0]].notna()]

# Reset index for clarity
df34_multi.reset_index(drop=True, inplace=True)

for col in df34_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18–54 - Number'
'Persons aged 18–54 - Proportion (%)'
'Persons aged 18–54 - Population'
'Persons aged 18–54 - 95% CI of proportion'
'Persons aged 18–54 - 95% CI of proportion.1'
'Persons aged 55–74 - Number'
'Persons aged 55–74 - Proportion (%)'
'Persons aged 55–74 - Population'
'Persons aged 55–74 - 95% CI of proportion'
'Persons aged 55–74 - 95% CI of proportion.1'
'Persons aged 75+ - Number'
'Persons aged 75+ - Proportion (%)'
'Persons aged 75+ - Population'
'Persons aged 75+ - 95% CI of proportion'
'Persons aged 75+ - 95% CI of proportion.1'
'Males aged 18–54 - Number'
'Males aged 18–54 - Proportion (%)'
'Males aged 18–54 - Population'
'Males aged 18–54 - 95% CI of proportion'
'Males aged 18–54 - 95% CI of proportion.1'
'Males aged 55–74 - Number'
'Males aged 55–74 - Proportion (%)'
'Males aged 55–74 - Population'
'Males aged 55–74 - 95% CI of proportion'
'Males aged 55–74 - 95% CI of proportion.1'
'Males aged 75+ - Number'
'Males aged 75+ - Proportion (%)'
'Males aged 75+ - Population'
'Males aged 75+ - 95% CI of proportion'
'Males aged 75+ - 95% CI of proportion.1'
'Females aged 18–54 - Number'
'Females aged 18–54 - Proportion (%)'
'Females aged 18–54 - Population'
'Females aged 18–54 - 95% CI of proportion'
'Females aged 18–54 - 95% CI of proportion.1'
'Females aged 55–74 - Number'
'Females aged 55–74 - Proportion (%)'
'Females aged 55–74 - Population'
'Females aged 55–74 - 95% CI of proportion'
'Females aged 55–74 - 95% CI of proportion.1'
'Females aged 75+ - Number'
'Females aged 75+ - Proportion (%)'
'Females aged 75+ - Population'
'Females aged 75+ - 95% CI of proportion'

C:\Users\YOGA\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Conditional Formatting extension is not supported and will be removed
  for idx, row in parser.parse():

In [58]:
import pandas as pd

# Step 1: Rename key columns for simplicity
df34_multi.rename(columns={
    df34_multi.columns[0]: "Code",
    df34_multi.columns[1]: "Region"  
}, inplace=True)

# Step 2: Clean column names
df34_multi.columns = df34_multi.columns.str.strip()

# Step 3: Select relevant columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18–54 - Number',
    'Persons aged 18–54 - Proportion (%)',
    'Persons aged 18–54 - Population',
    'Persons aged 18–54 - 95% CI of proportion',
    'Persons aged 55–74 - Number',
    'Persons aged 55–74 - Proportion (%)',
    'Persons aged 55–74 - Population',
    'Persons aged 55–74 - 95% CI of proportion',
    'Persons aged 75+ - Number',
    'Persons aged 75+ - Proportion (%)',
    'Persons aged 75+ - Population',
    'Persons aged 75+ - 95% CI of proportion',
    'Males aged 18–54 - Number',
    'Males aged 18–54 - Proportion (%)',
    'Males aged 18–54 - Population',
    'Males aged 18–54 - 95% CI of proportion',
    'Males aged 55–74 - Number',
    'Males aged 55–74 - Proportion (%)',
    'Males aged 55–74 - Population',
    'Males aged 55–74 - 95% CI of proportion',
    'Males aged 75+ - Number',
    'Males aged 75+ - Proportion (%)',
    'Males aged 75+ - Population',
    'Males aged 75+ - 95% CI of proportion',
    'Females aged 18–54 - Number',
    'Females aged 18–54 - Proportion (%)',
    'Females aged 18–54 - Population',
    'Females aged 18–54 - 95% CI of proportion',
    'Females aged 55–74 - Number',
    'Females aged 55–74 - Proportion (%)',
    'Females aged 55–74 - Population',
    'Females aged 55–74 - 95% CI of proportion',
    'Females aged 75+ - Number',
    'Females aged 75+ - Proportion (%)',
    'Females aged 75+ - Population',
    'Females aged 75+ - 95% CI of proportion'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df34_multi.columns]
df34_selected = df34_multi[selected_columns].copy()

# Step 4: Melt to long format
df34_final = pd.melt(
    df34_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df34_final["Gender"] = df34_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df34_final["AgeGroup"] = df34_final["Group_Metric"].str.extract(r'aged (.*) -')
df34_final["Metric"] = df34_final["Group_Metric"].str.extract(r'- (.*)$')
df34_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df34_final["Metric"] = df34_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df34_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    if ci_col in df_wide.columns:
        df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
        df_wide.drop(columns=ci_col, inplace=True)
    else:
        print(f"Skipping missing CI column: {ci_col}")


# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info (if column exists), else keep all
if 'Age_Standardised_Rate' in df_wide.columns:
    hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()
    print("Cleaned rows with missing 'Age_Standardised_Rate'")
else:
    hbp_df_clean = df_wide.copy()
    print("Age_Standardised_Rate' column not found — skipping dropna and continuing with full dataset.")


# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Obesity"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 11: Export to CSV
hbp_df_clean.to_csv("PHN_OB_AGE_SEX.csv", index=False, encoding='utf-8-sig')
print("Saved as 'PHN_OB_AGE_SEX.csv' successfully!")

Skipping missing CI column: CI_Standardised_Rate
Skipping missing CI column: CI_Rate_Ratio
Age_Standardised_Rate' column not found — skipping dropna and continuing with full dataset.
Missing values after cleaning:
 Metric
Code                   0
Region                 0
Gender                 0
AgeGroup               0
Number                 6
Population             6
CI_Proportion_Lower    0
CI_Proportion_Upper    0
Proportion (%)         6
Risk_Factor            0
dtype: int64
 Final shape: (279, 10)
Saved as 'PHN_OB_AGE_SEX.csv' successfully!

### 4.3 PHN_CS_SEX_2017-18

In [39]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df43 = xls.parse('4.3 PHN_CS_SEX_2017-18', skiprows=9)
df43.head()

,Unnamed: 0,Unnamed: 1,Persons aged 18+,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 18,Unnamed: 19,Females aged 18+,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,Code,Name,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio,...,95% CI rate ratio,NaN,Number,Proportion (%),95% CI of proportion,Population,Age-standardised rate (per 100),95% CI standardised rate,Rate ratio (relative to all of Australia),95% CI rate ratio
1,NaN,Australia,2766802.493191,14.831346,NaN,18655100,15.100844,(14.6–15.6),1,–,...,–,NaN,1130593.79492,11.884096,(11.3–12.4),9513503,12.07784,(11.5–12.6),1,–
2,PHN101,Central and Eastern Sydney,161718.8,12.662,(11.6–13.7),1277175,12.3,(11.3–13.4),0.79755,(0.7–0.9),...,(0.7–0.8),NaN,63545.55,9.814,(8.9–10.7),647508.3,10.107,(9.1–11.2),0.81987,(0.7–0.9)
3,PHN102,Northern Sydney,56402.69,7.965,(7.2–8.7),708127.2,7.912,(7.2–8.6),0.51298,(0.5–0.6),...,(0.5–0.6),NaN,23110.21,6.298,(5.7–6.9),366973.3,6.447,(5.7–7.2),0.52299,(0.5–0.6)
4,PHN103,Western Sydney,96040.86,13.257,(12.3–14.3),724473.6,12.792,(11.8–13.8),0.82944,(0.8–0.9),...,(0.7–0.8),NaN,38839.81,10.745,(9.9–11.6),361469.4,10.9,(9.9–11.9),0.88422,(0.8–1.0)

In [40]:
# Load with multi-level header (first 2 rows after skipping 9)
df43_multi = xls.parse('4.3 PHN_CS_SEX_2017-18', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df43_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df43_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df43_multi = df43_multi[df43_multi[df43_multi.columns[0]] != 'Code']
df43_multi = df43_multi[df43_multi[df43_multi.columns[0]].notna()]

# Reset index for clarity
df43_multi.reset_index(drop=True, inplace=True)

for col in df43_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18+ - Number'
'Persons aged 18+ - Proportion (%)'
'Persons aged 18+ - 95% CI of proportion'
'Persons aged 18+ - Population'
'Persons aged 18+ - Age-standardised rate (per 100)'
'Persons aged 18+ - 95% CI standardised rate'
'Persons aged 18+ - Rate ratio  (relative to all of Australia)'
'Persons aged 18+ - 95% CI rate ratio'
'Persons aged 18+ - 95% CI rate ratio.1'
'Males aged 18+ - Number'
'Males aged 18+ - Proportion (%)'
'Males aged 18+ - 95% CI of proportion'
'Males aged 18+ - Population'
'Males aged 18+ - Age-standardised rate (per 100)'
'Males aged 18+ - 95% CI standardised rate'
'Males aged 18+ - Rate ratio  (relative to all of Australia)'
'Males aged 18+ - 95% CI rate ratio'
'Males aged 18+ - 95% CI rate ratio.1'
'Females aged 18+ - Number'
'Females aged 18+ - Proportion (%)'
'Females aged 18+ - 95% CI of proportion'
'Females aged 18+ - Population'
'Females aged 18+ - Age-standardised rate (per 100)'
'Females aged 18+ - 95% CI standardised rate'
'Females aged 18+ - Rate ratio  (relative to all of Australia)'
'Females aged 18+ - 95% CI rate ratio'

In [59]:
import pandas as pd

# Step 1: Rename key columns
df43_multi.rename(columns={
    df43_multi.columns[0]: "Code",
    df43_multi.columns[1]: "Region"
}, inplace=True)

# Step 2: Clean up all column names properly
df43_multi.columns = df43_multi.columns.str.strip()
df43_multi.columns = df43_multi.columns.str.replace('–', '-', regex=False)  # fix en dash
df43_multi.columns = df43_multi.columns.str.replace('  ', ' ', regex=False)  # fix double spaces
df43_multi.columns = df43_multi.columns.str.replace(' (relative to all of Australia)', '', regex=False)  # 🛠 remove extra part after Rate ratio

# Step 3: Now corrected selected columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18+ - Number',
    'Persons aged 18+ - Proportion (%)',
    'Persons aged 18+ - 95% CI of proportion',
    'Persons aged 18+ - Population',
    'Persons aged 18+ - Age-standardised rate (per 100)',
    'Persons aged 18+ - 95% CI standardised rate',
    'Persons aged 18+ - Rate ratio',
    'Persons aged 18+ - 95% CI rate ratio',
    'Males aged 18+ - Number',
    'Males aged 18+ - Proportion (%)',
    'Males aged 18+ - 95% CI of proportion',
    'Males aged 18+ - Population',
    'Males aged 18+ - Age-standardised rate (per 100)',
    'Males aged 18+ - 95% CI standardised rate',
    'Males aged 18+ - Rate ratio',
    'Males aged 18+ - 95% CI rate ratio',
    'Females aged 18+ - Number',
    'Females aged 18+ - Proportion (%)',
    'Females aged 18+ - 95% CI of proportion',
    'Females aged 18+ - Population',
    'Females aged 18+ - Age-standardised rate (per 100)',
    'Females aged 18+ - 95% CI standardised rate',
    'Females aged 18+ - Rate ratio',
    'Females aged 18+ - 95% CI rate ratio'
]

# Select available columns safely
existing_columns = [col for col in selected_columns if col in df43_multi.columns]
df43_selected = df43_multi[selected_columns].copy()

# Step 4: Melt to long format
df43_final = pd.melt(
    df43_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df43_final["Gender"] = df43_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df43_final["AgeGroup"] = df43_final["Group_Metric"].str.extract(r'aged (.*) -')
df43_final["Metric"] = df43_final["Group_Metric"].str.extract(r'- (.*)$')
df43_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df43_final["Metric"] = df43_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df43_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns
def split_ci(ci_value):
    if isinstance(ci_value, str) and '–' in ci_value:
        parts = ci_value.strip("()").split("–")
        try:
            return float(parts[0]), float(parts[1])
        except:
            return None, None
    return None, None

for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
    df_wide.drop(columns=ci_col, inplace=True)

# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
# Step 12: Drop rows with missing standardised rate info and copy
hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()

# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Current Smoker"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 12: Save to CSV
hbp_df_clean.to_csv("PHN_CS_SEX_2017-18.csv", index=False, encoding='utf-8-sig')
print("\n File saved as 'PHN_CS_SEX_2017-18.csv' successfully!")

Missing values after cleaning:
 Metric
Code                          0
Region                        0
Gender                        0
AgeGroup                      0
Age_Standardised_Rate         0
Number                        0
Population                    0
Rate ratio                    0
CI_Proportion_Lower           0
CI_Proportion_Upper           0
CI_Standardised_Rate_Lower    0
CI_Standardised_Rate_Upper    0
CI_Rate_Ratio_Lower           0
CI_Rate_Ratio_Upper           0
Proportion (%)                0
Risk_Factor                   0
dtype: int64
 Final shape: (93, 16)

 File saved as 'PHN_CS_SEX_2017-18.csv' successfully!

### 4.4 PHN_CS_AGE&SEX

In [42]:
# Load and preview the 'PHA_CVD_DEATH_SEX' sheet
df44 = xls.parse('4.4 PHN_CS_AGE&SEX', skiprows=9)
df44.head()

,Unnamed: 0,Unnamed: 1,Persons aged 18–54,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Persons aged 55–74,Unnamed: 8,Unnamed: 9,...,Unnamed: 36,Females aged 55–74,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Females aged 75+,Unnamed: 43,Unnamed: 44,Unnamed: 45
0,Code,Name,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,...,NaN,Number,Proportion (%),Population,95% CI of proportion,NaN,Number,Proportion (%),Population,95% CI of proportion
1,NaN,Australia,2056926.057486,16.83472,12218356,(16.2–17.5),NaN,641084.069909,12.922115,4981923.951862,...,NaN,295142.163538,11.614576,2556545.794198,(10.7–12.5),NaN,32499.550692,4.036584,789715.205802,(3.1–5.0)
2,PHN101,Central and Eastern Sydney,129012.5,14.037,919113.8,(12.8–15.2),NaN,29003.1,10.704,270965.3,...,NaN,14321.66,10.23,140001.2,(9.2–11.3),NaN,2011.99,4.157,48400.83,(3.4–4.9)
3,PHN102,Northern Sydney,43568.47,9.274,469801.6,(8.4–10.1),NaN,11379.99,6.398,177864.8,...,NaN,5668.674,6.137,92363.79,(5.5–6.8),NaN,785.79,2.331,33717.17,(1.8–2.8)
4,PHN103,Western Sydney,74617.62,14.25,523649.6,(13.1–15.4),NaN,19432.63,12.094,160684.8,...,NaN,9761.812,11.881,82163.25,(10.9–12.9),NaN,1115.299,5.044,22111.71,(4.2–5.9)

In [43]:
# Load with multi-level header (first 2 rows after skipping 9)
df44_multi = xls.parse('4.4 PHN_CS_AGE&SEX', skiprows=9, header=[0, 1])

# Flatten multi-level headers: Combine both header rows into a single line with clear labels
df44_multi.columns = [
    f"{str(col1).strip()} - {str(col2).strip()}" if str(col2).strip() != 'nan' else str(col1).strip()
    for col1, col2 in df44_multi.columns
]

# Remove rows where the 'Code' column is NaN (region code column will contain 'Code' string)
df44_multi = df44_multi[df44_multi[df44_multi.columns[0]] != 'Code']
df44_multi = df44_multi[df44_multi[df44_multi.columns[0]].notna()]

# Reset index for clarity
df44_multi.reset_index(drop=True, inplace=True)

for col in df44_multi.columns:
    print(repr(col))

'Unnamed: 0_level_0 - Code'
'Unnamed: 1_level_0 - Name'
'Persons aged 18–54 - Number'
'Persons aged 18–54 - Proportion (%)'
'Persons aged 18–54 - Population'
'Persons aged 18–54 - 95% CI of proportion'
'Persons aged 18–54 - 95% CI of proportion.1'
'Persons aged 55–74 - Number'
'Persons aged 55–74 - Proportion (%)'
'Persons aged 55–74 - Population'
'Persons aged 55–74 - 95% CI of proportion'
'Persons aged 55–74 - 95% CI of proportion.1'
'Persons aged 75+ - Number'
'Persons aged 75+ - Proportion (%)'
'Persons aged 75+ - Population'
'Persons aged 75+ - 95% CI of proportion'
'Persons aged 75+ - 95% CI of proportion.1'
'Males aged 18–54 - Number'
'Males aged 18–54 - Proportion (%)'
'Males aged 18–54 - Population'
'Males aged 18–54 - 95% CI of proportion'
'Males aged 18–54 - 95% CI of proportion.1'
'Males aged 55–74 - Number'
'Males aged 55–74 - Proportion (%)'
'Males aged 55–74 - Population'
'Males aged 55–74 - 95% CI of proportion'
'Males aged 55–74 - 95% CI of proportion.1'
'Males aged 75+ - Number'
'Males aged 75+ - Proportion (%)'
'Males aged 75+ - Population'
'Males aged 75+ - 95% CI of proportion'
'Males aged 75+ - 95% CI of proportion.1'
'Females aged 18–54 - Number'
'Females aged 18–54 - Proportion (%)'
'Females aged 18–54 - Population'
'Females aged 18–54 - 95% CI of proportion'
'Females aged 18–54 - 95% CI of proportion.1'
'Females aged 55–74 - Number'
'Females aged 55–74 - Proportion (%)'
'Females aged 55–74 - Population'
'Females aged 55–74 - 95% CI of proportion'
'Females aged 55–74 - 95% CI of proportion.1'
'Females aged 75+ - Number'
'Females aged 75+ - Proportion (%)'
'Females aged 75+ - Population'
'Females aged 75+ - 95% CI of proportion'

In [64]:
import pandas as pd

# Step 1: Rename the first two columns
df44_multi.rename(columns={
    df44_multi.columns[0]: "Code",
    df44_multi.columns[1]: "Region"
}, inplace=True)

# Step 2: Clean column names fully
df44_multi.columns = df44_multi.columns.str.strip()
df44_multi.columns = df44_multi.columns.str.replace('–', '-', regex=False)  # fix en dash
df44_multi.columns = df44_multi.columns.str.replace('  ', ' ', regex=False)  # fix double spaces

# Step 3: Corrected selected columns
selected_columns = [
    "Code", "Region",
    'Persons aged 18-54 - Number',
    'Persons aged 18-54 - Proportion (%)',
    'Persons aged 18-54 - Population',
    'Persons aged 18-54 - 95% CI of proportion',
    'Persons aged 55-74 - Number',
    'Persons aged 55-74 - Proportion (%)',
    'Persons aged 55-74 - Population',
    'Persons aged 55-74 - 95% CI of proportion',
    'Persons aged 75+ - Number',
    'Persons aged 75+ - Proportion (%)',
    'Persons aged 75+ - Population',
    'Persons aged 75+ - 95% CI of proportion',
    'Males aged 18-54 - Number',
    'Males aged 18-54 - Proportion (%)',
    'Males aged 18-54 - Population',
    'Males aged 18-54 - 95% CI of proportion',
    'Males aged 55-74 - Number',
    'Males aged 55-74 - Proportion (%)',
    'Males aged 55-74 - Population',
    'Males aged 55-74 - 95% CI of proportion',
    'Males aged 75+ - Number',
    'Males aged 75+ - Proportion (%)',
    'Males aged 75+ - Population',
    'Males aged 75+ - 95% CI of proportion',
    'Females aged 18-54 - Number',
    'Females aged 18-54 - Proportion (%)',
    'Females aged 18-54 - Population',
    'Females aged 18-54 - 95% CI of proportion',
    'Females aged 55-74 - Number',
    'Females aged 55-74 - Proportion (%)',
    'Females aged 55-74 - Population',
    'Females aged 55-74 - 95% CI of proportion',
    'Females aged 75+ - Number',
    'Females aged 75+ - Proportion (%)',
    'Females aged 75+ - Population',
    'Females aged 75+ - 95% CI of proportion'
]

# Step 3: Select only relevant columns
df44_selected = df44_multi[selected_columns].copy()

# Step 4: Melt to long format
df44_final = pd.melt(
    df44_selected,
    id_vars=["Code", "Region"],
    var_name="Group_Metric",
    value_name="Value"
)

# Step 6: Assign Gender and AgeGroup, clean Metric labels
df44_final["Gender"] = df44_final["Group_Metric"].str.extract(r'^(Persons|Males|Females)')
df44_final["AgeGroup"] = df44_final["Group_Metric"].str.extract(r'aged (.*) -')
df44_final["Metric"] = df44_final["Group_Metric"].str.extract(r'- (.*)$')
df44_final.drop(columns="Group_Metric", inplace=True)

# Step 7: Standardize metric names
df44_final["Metric"] = df44_final["Metric"].replace({
    "95% CI of proportion": "CI_Proportion",
    "95% CI standardised rate": "CI_Standardised_Rate",
    "95% CI rate ratio": "CI_Rate_Ratio",
    "Proportion (%)": "Proportion",
    "Rate ratio  (relative to all of Australia)": "Rate_Ratio",  # double space!
    "Age-standardised rate (per 100)": "Age_Standardised_Rate"
})

# Step 8: Pivot to wide format
df_wide = df44_final.pivot_table(
    index=["Code", "Region", "Gender", "AgeGroup"],
    columns="Metric",
    values="Value",
    aggfunc="first"
).reset_index()

# Step 9: Split confidence intervals into lower/upper columns safely
for ci_col in ['CI_Proportion', 'CI_Standardised_Rate', 'CI_Rate_Ratio']:
    if ci_col in df_wide.columns:
        df_wide[f"{ci_col}_Lower"], df_wide[f"{ci_col}_Upper"] = zip(*df_wide[ci_col].apply(split_ci))
        df_wide.drop(columns=ci_col, inplace=True)
    else:
        print(f" Column '{ci_col}' not found. Skipping.")


# Step 10: Convert proportion to percent format (round to 2 decimals)
df_wide["Proportion (%)"] = pd.to_numeric(df_wide["Proportion"], errors="coerce").round(2)
df_wide.drop(columns="Proportion", inplace=True)

# Step 11: Convert remaining metrics to numeric
numeric_cols = [col for col in df_wide.columns if col not in ["Code", "Region", "Gender", "AgeGroup"]]
for col in numeric_cols:
    df_wide[col] = pd.to_numeric(df_wide[col], errors="coerce")

# Cleaning Steps
if 'Age_Standardised_Rate' in df_wide.columns:
    hbp_df_clean = df_wide.dropna(subset=['Age_Standardised_Rate']).copy()
    print("Dropped rows with missing 'Age_Standardised_Rate'")
else:
    hbp_df_clean = df_wide.copy()
    print("Age_Standardised_Rate' not found. Skipping dropna on this column.")


# Step 13: Standardize Region names (safe assignment)
hbp_df_clean.loc[:, 'Region'] = hbp_df_clean['Region'].str.strip().str.upper()

# Step 14: Reset index
hbp_df_clean.reset_index(drop=True, inplace=True)

# Step 14.1: Add Risk_Factor column
hbp_df_clean["Risk_Factor"] = "Current Smoker"

# Step 15: Confirm cleaning
print("Missing values after cleaning:\n", hbp_df_clean.isnull().sum())
print(" Final shape:", hbp_df_clean.shape)
# Step 12: Export to CSV
hbp_df_clean.to_csv("PHN_CS_AGE&SEX.csv", index=False, encoding='utf-8-sig')
print("\n File saved as 'PHN_CS_AGE&SEX.csv' successfully!")

 Column 'CI_Standardised_Rate' not found. Skipping.
 Column 'CI_Rate_Ratio' not found. Skipping.
Age_Standardised_Rate' not found. Skipping dropna on this column.
Missing values after cleaning:
 Metric
Code                   0
Region                 0
Gender                 0
AgeGroup               0
Number                 7
Population             3
CI_Proportion_Lower    3
CI_Proportion_Upper    3
Proportion (%)         5
Risk_Factor            0
dtype: int64
 Final shape: (279, 10)

 File saved as 'PHN_CS_AGE&SEX.csv' successfully!

### Merge:

In [75]:
import pandas as pd

# Step 1: Define file paths
file_paths = {
    "PHN_CS_AGE_SEX": "PHN_CS_AGE&SEX.csv",
    "PHN_OB_AGE_SEX": "PHN_OB_AGE_SEX.csv",
    "PHN_IPA_AGE_SEX": "PHN_IPA_AGE_SEX.csv",
    "PHN_HBP_AGE_SEX": "PHN_HBP_AGE_SEX.csv",
}

# Step 2: Load datasets
dataframes = {name: pd.read_csv(path) for name, path in file_paths.items()}

# Step 3: Get union of all columns
all_columns = sorted(set().union(*(df.columns for df in dataframes.values())))

# Step 4: Standardize all DataFrames to the same columns
aligned_dfs = []
for name, df in dataframes.items():
    aligned_df = df.copy()
    for col in all_columns:
        if col not in aligned_df.columns:
            aligned_df[col] = pd.NA
    aligned_df = aligned_df[all_columns]  # reorder
    aligned_df["Source_File"] = name
    aligned_dfs.append(aligned_df)

# Step 5: Strictly filter out DataFrames that are all-NA by row or column
non_empty_dfs = []
for name, df in zip(file_paths.keys(), aligned_dfs):
    # Check: at least one non-NA row and one non-NA column
    if df.dropna(how="all").shape[0] > 0 and df.dropna(axis=1, how="all").shape[1] > 0:
        non_empty_dfs.append(df)
    else:
        print(f"Skipped: {name} (empty or all-NA content)")

# Step 6: Concatenate without warning
if non_empty_dfs:
    merged_df = pd.concat(non_empty_dfs, ignore_index=True)
# Add Year column
    merged_df["Year"] = "2017–2018"

    merged_df.to_csv("Risk_Factors.csv", index=False, encoding="utf-8-sig")
    print(" Merged file saved as 'Risk_Factors.csv'")
else:
    print(" No valid data to merge.")

FileNotFoundError: [Errno 2] No such file or directory: 'PHN_CS_AGE&SEX.csv'

In [74]:
import pandas as pd

# Load the dataset
df = pd.read_csv("Risk_Factors.csv")

# Step 1: Drop rows missing critical group info
df = df.dropna(subset=["AgeGroup", "Gender", "Region", "Risk_Factor"])

# Step 2: Fill missing CI values with median
df["CI_Proportion_Lower"] = df["CI_Proportion_Lower"].fillna(df["CI_Proportion_Lower"].median())
df["CI_Proportion_Upper"] = df["CI_Proportion_Upper"].fillna(df["CI_Proportion_Upper"].median())

# Step 3: Impute other numeric columns using group-wise means
df["Number"] = df.groupby(["Region", "Gender", "Risk_Factor"])["Number"].transform(lambda x: x.fillna(x.mean()))
df["Population"] = df.groupby(["Region", "Gender", "Risk_Factor"])["Population"].transform(lambda x: x.fillna(x.mean()))
df["Proportion (%)"] = df.groupby(["Region", "Gender", "Risk_Factor"])["Proportion (%)"].transform(lambda x: x.fillna(x.mean()))

# Step 4: Drop the Source_File column
if "Source_File" in df.columns:
    df = df.drop(columns=["Source_File"])

# Step 5: Save final cleaned version
df.to_csv("Risk_Factors_CVD.csv", index=False, encoding="utf-8-sig")
print("Cleaned and saved as 'Risk_Factors_CVD.csv'")

Cleaned and saved as 'Risk_Factors_CVD.csv'